#!/bin/bash

cd "/etc/tinc/$NETNAME" \
    || cd "/usr/local/etc/tinc/$NETNAME" \
    || cd "/opt/local/etc/tinc/$NETNAME" \
    || exit 1

ip6_net=$(sed -nE 's_Subnet[ ]*=[ ]*([[:xdigit:]:]+):/64_\1_p' "hosts/$NAME")
sysname=$(uname)

if [ "$sysname" = Linux ]; then
    test -f /etc/openwrt_release && ubus -t 15 wait_for network.interface.cvnet
    ip link set "$INTERFACE" up
    ip address add "$ip6_net:1/48" dev "$INTERFACE"
elif [ "$sysname" = FreeBSD ] || [ "$sysname" = OpenBSD ] || [ "$sysname" = Darwin ]; then
    ifconfig "$INTERFACE" up
    ifconfig "$INTERFACE" inet6 "$ip6_net:1/48" prefixlen 48
fi
